### ISSUE TITLE
North american hosts in links are not matched

### ISSUE THREAD

**Issue by gavanderhoorn** [GjjvdBurg/safelinksfixer#3]
Seems #1 was not generic enough: I've come across links that don't have `eurNN` but `namNN` in the rewritten URL.

Example: `https://nam01.safelinks.protection.outlook.com/?url=`

Is there a specific reason the `eurNN` part is included in the regex?

**Comment by GjjvdBurg** [comment]
Oh that's interesting, looks like it's a [geo code](https://docs.microsoft.com/en-us/office365/enterprise/multi-geo-tenant-configuration). I didn't have a specific reason, mainly that's the only URLs that I saw when I started with it. We can replace it with a simple ``.*`` then.
